"""
Phase 11 Shared Constants, State Definitions, and Authoritative Gate Criteria for SIGNOVA.
"""

from typing import List, Set

# Supervision State Machine
SUPERVISION_STATE_C = "STATE_C"  # No sequential supervision available
SUPERVISION_STATE_B = "STATE_B"  # Annotation platform/infrastructure ready; human data pending/in-progress
SUPERVISION_STATE_A = "STATE_A"  # Fully verified sequential ISL dataset available for CTC training

# Operational Status Identifiers
STATUS_OPERATIONAL = "OPERATIONAL"
STATUS_NOT_STARTED = "NOT_STARTED"
STATUS_BLOCKED_HUMAN_RESOURCE = "BLOCKED_HUMAN_RESOURCE"
STATUS_BLOCKED = "BLOCKED"
STATUS_UNLOCKED = "UNLOCKED"

# Review State Machine (Session Workflow: OPEN -> DRAFT -> SAVE -> RESUME -> SUBMIT -> REVIEW -> VERIFY/REJECT)
REVIEW_STATE_UNANNOTATED = "UNANNOTATED"
REVIEW_STATE_ANNOTATION_IN_PROGRESS = "ANNOTATION_IN_PROGRESS"
REVIEW_STATE_ANNOTATED = "ANNOTATED"
REVIEW_STATE_SECOND_ANNOTATION_PENDING = "SECOND_ANNOTATION_PENDING"
REVIEW_STATE_DISAGREEMENT = "DISAGREEMENT"
REVIEW_STATE_REVIEW_PENDING = "REVIEW_PENDING"
REVIEW_STATE_VERIFIED = "VERIFIED"
REVIEW_STATE_REJECTED = "REJECTED"

ALL_REVIEW_STATES: Set[str] = {
    REVIEW_STATE_UNANNOTATED,
    REVIEW_STATE_ANNOTATION_IN_PROGRESS,
    REVIEW_STATE_ANNOTATED,
    REVIEW_STATE_SECOND_ANNOTATION_PENDING,
    REVIEW_STATE_DISAGREEMENT,
    REVIEW_STATE_REVIEW_PENDING,
    REVIEW_STATE_VERIFIED,
    REVIEW_STATE_REJECTED,
}

# Quality Grades
QUALITY_UNVERIFIED = "UNVERIFIED"
QUALITY_WEAK = "WEAK"
QUALITY_PARTIAL = "PARTIAL"
QUALITY_VERIFIED = "VERIFIED"
QUALITY_LINGUIST_REVIEWED = "LINGUIST_REVIEWED"

ALL_QUALITY_GRADES: Set[str] = {
    QUALITY_UNVERIFIED,
    QUALITY_WEAK,
    QUALITY_PARTIAL,
    QUALITY_VERIFIED,
    QUALITY_LINGUIST_REVIEWED,
}

# Disagreement Taxonomy
DISAGREEMENT_TOKEN_IDENTITY = "TOKEN_IDENTITY"
DISAGREEMENT_TOKEN_ORDER = "TOKEN_ORDER"
DISAGREEMENT_SEGMENT_BOUNDARY = "SEGMENT_BOUNDARY"
DISAGREEMENT_OMITTED_SIGN = "OMITTED_SIGN"
DISAGREEMENT_EXTRA_SIGN = "EXTRA_SIGN"
DISAGREEMENT_UNCERTAIN_SIGN = "UNCERTAIN_SIGN"
DISAGREEMENT_MULTIPLE_PLAUSIBLE_INTERPRETATIONS = "MULTIPLE_PLAUSIBLE_INTERPRETATIONS"
DISAGREEMENT_OTHER = "OTHER"

ALL_DISAGREEMENT_TYPES: Set[str] = {
    DISAGREEMENT_TOKEN_IDENTITY,
    DISAGREEMENT_TOKEN_ORDER,
    DISAGREEMENT_SEGMENT_BOUNDARY,
    DISAGREEMENT_OMITTED_SIGN,
    DISAGREEMENT_EXTRA_SIGN,
    DISAGREEMENT_UNCERTAIN_SIGN,
    DISAGREEMENT_MULTIPLE_PLAUSIBLE_INTERPRETATIONS,
    DISAGREEMENT_OTHER,
}

# Reserved CTC / Tokenizer Vocabulary Tokens
BLANK_TOKEN = "<BLANK>"
BLANK_ID = 0
UNK_TOKEN = "<UNK>"
UNK_ID = 1

# Authoritative 12 STATE_A Real CTC Training Prerequisites
EXACT_12_STATE_A_CONDITIONS: List[str] = [
    "GENUINE_SEQUENTIAL_ANNOTATIONS_EXIST",
    "VIDEO_ANNOTATION_PAIRING_VERIFIED",
    "ANNOTATION_SCHEMA_VALIDATION_PASSED",
    "VOCABULARY_DERIVED_FROM_GENUINE_ANNOTATIONS",
    "ANNOTATION_QUALITY_MEETS_TRAINING_THRESHOLD",
    "REQUIRED_HUMAN_REVIEW_COMPLETE",
    "NO_CRITICAL_LEAKAGE_DETECTED",
    "DATASET_PROVENANCE_RECORDED",
    "LICENSING_ACCESS_STATUS_RECORDED",
    "TRAIN_VAL_TEST_SPLIT_VALID",
    "SIGNER_SESSION_INDEPENDENCE_CHARACTERIZED",
    "MINIMUM_SAMPLE_THRESHOLD_SATISFIED",
]
