"""
Phase 13 Pilot Constants, Dataset Classifications, and Split Strategies for SIGNOVA.
"""

from typing import Dict, List, Set

# Dataset Scale Classifications
DATASET_SCALE_NO_DATA = "NO_DATA"
DATASET_SCALE_PILOT_ONLY = "PILOT_ONLY"
DATASET_SCALE_DATA_LIMITED = "DATA_LIMITED"
DATASET_SCALE_RESEARCH_SCALE = "RESEARCH_SCALE"

ALL_DATASET_SCALES: Set[str] = {
    DATASET_SCALE_NO_DATA,
    DATASET_SCALE_PILOT_ONLY,
    DATASET_SCALE_DATA_LIMITED,
    DATASET_SCALE_RESEARCH_SCALE,
}

# Split Strategy Hierarchy
SPLIT_STRATEGY_SIGNER_INDEPENDENT = "SIGNER_INDEPENDENT"
SPLIT_STRATEGY_SESSION_INDEPENDENT = "SESSION_INDEPENDENT"
SPLIT_STRATEGY_SOURCE_GROUP_INDEPENDENT = "SOURCE_GROUP_INDEPENDENT"
SPLIT_STRATEGY_RANDOM = "RANDOM"

# Human Resource Availability
HUMAN_RESOURCE_AVAILABLE = "HUMAN_RESOURCE_AVAILABLE"
HUMAN_RESOURCE_PARTIAL = "HUMAN_RESOURCE_PARTIAL"
HUMAN_RESOURCE_UNAVAILABLE = "HUMAN_RESOURCE_UNAVAILABLE"

# Generalization Claims
CLAIMS_NOT_READY = "NOT_READY"
CLAIMS_LIMITED = "LIMITED"
CLAIMS_PERMITTED_BY_EVIDENCE = "PERMITTED_BY_EVIDENCE"
