"""
Phase 14 Annotation Operations Constants for SIGNOVA.
"""

from typing import Dict, List, Set

# Agreement Status Constants
AGREEMENT_NOT_COMPUTABLE = "NOT_COMPUTABLE"
AGREEMENT_COMPUTABLE = "COMPUTABLE"
AGREEMENT_INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"

ALL_AGREEMENT_STATUSES: Set[str] = {
    AGREEMENT_NOT_COMPUTABLE,
    AGREEMENT_COMPUTABLE,
    AGREEMENT_INSUFFICIENT_SAMPLE,
}

# Double Annotation Policy Configuration
DEFAULT_DOUBLE_ANNOTATION_FRACTION: float = 0.20
DEFAULT_DOUBLE_ANNOTATION_MINIMUM: int = 5

# Split Strategies
SPLIT_STRATEGY_SIGNER_INDEPENDENT = "SIGNER_INDEPENDENT"
SPLIT_STRATEGY_SESSION_INDEPENDENT = "SESSION_INDEPENDENT"
SPLIT_STRATEGY_SOURCE_GROUP_INDEPENDENT = "SOURCE_GROUP_INDEPENDENT"
SPLIT_STRATEGY_RANDOM = "RANDOM"

# Artifact Status Codes
ARTIFACT_STATUS_CREATED = "CREATED"
ARTIFACT_STATUS_BLOCKED = "BLOCKED"
ARTIFACT_STATUS_PREEXISTING = "PREEXISTING_ARTIFACT"
